name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Transfer build artifacts to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist" # 로컬(러너)의 dist 폴더
          target: "${{ secrets.SERVER_PROJECT_PATH }}" # 서버의 프로젝트 경로 (이곳에 dist 폴더가 생성됨)
          overwrite: true

      - name: Restart PM2 process on server
        uses: appleboy/ssh-action@v1.0.3 # 최신 버전 확인 권장
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SERVER_PROJECT_PATH }}
            echo "Restarting PM2 process: aissue"
            pm2 restart aissue
            echo "PM2 process status:"
            pm2 list
